### ISSUE TITLE
No module named 'cv2' pip安装后仍然报错

### ISSUE THREAD

**Issue by evestorm** [ZKeeer/WeChatForRevocation#16]
终端报错信息：
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from execution import Execution
  File "/Users/macbook/Desktop/WeChatAssistant-master/execution.py", line 12, in <module>
    from takephoto import TakeGIF
  File "/Users/macbook/Desktop/WeChatAssistant-master/takephoto.py", line 4, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

通过在 https://stackoverflow.com/questions/19876079/opencv-cannot-find-module-cv2 下查询安装
opencv-python 后依然无效，报同样的错误...  
请问还需要下载什么吗？

**Comment by ZKeeer** [comment]
@evestorm 抱歉，我上传了错误文件，请把takephoto.py文件删除即可解决你的问题。现在拍照功能还没打算上线，所以没有做详尽的测试。

**Comment by ZKeeer** [comment]
@evestorm 建议重新下载。我把错误上传的文件删了，留下可用的了

**Comment by evestorm** [comment]
好的，谢谢~

**Comment by XAS-712** [comment]
@ZKeeer 一般建议至少两个branch，一个是master，存放稳定版，另一个是testing/developing，存放开发中的版本，这样可以避免别人不从release下载而直接git clone时下载到开发中的版本
