### ISSUE TITLE
执行python3 Main.py后报错

### ISSUE THREAD

**Issue by rqd1995** [ZKeeer/WeChatForRevocation#2]
Getting uuid of QR code.
Downloading QR code.
Traceback (most recent call last):
  File "Main.py", line 54, in <module>
    itchat.auto_login(hotReload=True)
  File "/usr/local/lib/python3.4/dist-packages/itchat/components/register.py", line 32, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/usr/local/lib/python3.4/dist-packages/itchat/components/login.py", line 45, in login
    picDir=picDir, qrCallback=qrCallback)
  File "/usr/local/lib/python3.4/dist-packages/itchat/components/login.py", line 118, in get_QR
    utils.print_qr(picDir)
  File "/usr/local/lib/python3.4/dist-packages/itchat/utils.py", line 83, in print_qr
    subprocess.call(['xdg-open', fileDir])
  File "/usr/lib/python3.4/subprocess.py", line 537, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'xdg-open'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Main.py", line 57, in <module>
    mylog.WriteLog(e)
  File "/home/wechat/WeChatForRevocation/log.py", line 19, in WriteLog
    fw.write(time.ctime() + "\n" + msg + "\n\n\n")
TypeError: Can't convert 'FileNotFoundError' object to str implicitly

系统使用debian8.2 x32 python3.4，已安装itchat（用pip3安装）

**Comment by ZKeeer** [comment]
@rqd1995 我在windows下编码，相关路径，你按照linux编码进行调整。

**Comment by MyZiegler** [comment]
需要调整哪呢啊 @rqd1995 
![aaaaaaaaa](https://user-images.githubusercontent.com/31609619/30033388-913f9970-91cd-11e7-890a-ebbf786c17fe.png)

**Comment by XAS-712** [comment]
可以看到zlib没装，需要先装上，不然Pillow可能不能用
