### ISSUE TITLE
web 版本报错，提示找不到bootstrap3模块

### ISSUE THREAD

**Issue by ZKeeer** [ZKeeer/WeChatForRevocation#23]
@chenqiuyuan 报错信息如下：
```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x00000236A6BAEC80>
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\django\utils\autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\django\core\management\commands\runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "C:\Anaconda3\lib\site-packages\django\utils\autoreload.py", line 250, in raise_last_exception
    six.reraise(*_exception)
  File "C:\Anaconda3\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Anaconda3\lib\site-packages\django\utils\autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Anaconda3\lib\site-packages\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "C:\Anaconda3\lib\site-packages\django\apps\config.py", line 94, in create
    module = import_module(entry)
  File "C:\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'bootstrap3'
```

**Comment by SLiNv** [comment]
根据python的版本安装
```pip install django-bootstrap3``` or
```pip3 install django-bootstrap3```

**Comment by chenqiuyuan** [comment]
requirements.txt除了itchat添加
Django和Django-bootstrap3
